version: '3.8'

services:
  node-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf  # Assurez-vous que le fichier mongod.conf existe dans votre répertoire local
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
